<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Transporteren_order" Id="{cf28c6dd-7fed-4d27-8b70-7f0672827bc6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Transporteren_order
VAR
	currentState : Taks_2 : Task_2.Inladen;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CASE currentState OF
	Task_2.Inladen:
	//Inladen van de order die is verwerkt in taak 1
	IF 
END_CASE]]></ST>
    </Implementation>
    <LineIds Name="Transporteren_order">
      <LineId Id="5" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>